require 'vagrant-openstack-cloud-provider'

Vagrant.configure("2") do |config|

  # This is a publicly available dummy box.
  config.vm.box = "sharpie/dummy"

  config.vm.provider :openstack do |os|
    os.username = "${OS_USERNAME}"
    os.api_key  = "${OS_PASSWORD}"
    os.flavor   = /m1.tiny/
    os.image    = /Ubuntu/
    os.endpoint = "${OS_AUTH_URL}" # such as http://openstack.invalid/ without /v3/auth/tokens
    os.keypair_name = "" # Your keypair name
    os.ssh_username = "" # Your image SSH username
    os.public_network_name = "public" # Your Neutron network name
    os.networks = %w() # Additional neutron networks
    os.region = "${OS_REGION_NAME}"
    os.project_name = "${OS_PROJECT_NAME}"
    os.project_domain_id = "${OS_PROJECT_DOMAIN_ID}"
    os.user_domain_name = "${OS_USER_DOMAIN_NAME}"
    os.identity_api_version = 'v3'
  end
end
